# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###
GET http://127.0.0.1:8000/accounts/1/transactions
Accept: application/json

###
GET http://127.0.0.1:8000/contracts/steth/total_shares
Accept: application/json

###
GET http://127.0.0.1:8000/contracts/steth/total_pooled_eth
Accept: application/json